### ISSUE TITLE
Application does not start up when combining this image and a database connection in Linux CentOS.

### ISSUE THREAD

**Issue by jda5** [tiangolo/uvicorn-gunicorn-fastapi-docker#196]
### Example Code

**main.py**

```
"""
Running this file will start-up the API. It imports the 
requisite modules, instantiates the fastapi app, configures the app, 
instantiates the Api and adds the resources to the API.

Attributes:
    app (FastAPI): The fastapi app. 
"""

from fastapi import FastAPI
from database import db
from endpoints import ingredient, recipe, recipe_ingredient

app = FastAPI()

app.include_router(ingredient.router)
app.include_router(recipe_ingredient.router)
app.include_router(recipe.router)

@app.on_event("startup")
async def startup():
    await db.connect()

@app.on_event("shutdown")
async def shutdown():
    await db.disconnect()
```

**database.py**

```
"""
This file simply fetches the environment variables and configures the database object
"""
import databases
from starlette.config import Config

config = Config(".env")

# Database configurations
_user = config("USER", cast=str)
_password = config("PASSWORD", cast=str)
_host = config("HOST", cast=str)
_database = config("DATABASE", cast=str)
_port = config("PORT", cast=int, default=3306)

db = databases.Database(
    f'mysql://{_user}:{_password}@{_host}/{_database}?port={_port}'
)
```

**docker-compose**

```
services:

  backend:                          # The app service definition
    container_name: backend
    build: .
    restart: always
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Dockerfile**

```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app
```

### Description

I created a Docker file and docker-compose file that makes use of the **tiangolo/uvicorn-gunicorn-fastapi**. On my local machine (Mac M1, iOS v12.5.1), after running `docker compose up`, everything boots up fine and I can interact with the database.

However, when I port this code to my server (Linux CentOS 7), the MySQL database boots up fine, but the workers created by gunicorn are stuck "waiting for application startup".

### Operating System

Linux

### Operating System Details

- Kernel Version: 3.10.0-1127.19.1.el7.x86_64
- Operating System: CentOS Linux 7 (Core)
- Architecture: x86_64

### FastAPI Version

0.85.1

### Python Version

3.9.5

### Additional Context

Here are the Docker logs after I run `docker compose up`. Notice how the workers start the server process but are stuck waiting for the application startup.

```
Attaching to backend
backend  | Checking for script in /app/prestart.sh
backend  | Running script /app/prestart.sh
backend  | Running inside /app/prestart.sh, you could add migrations to this file, e.g.:
backend  |
backend  | #! /usr/bin/env bash
backend  |
backend  | # Let the DB start
backend  | sleep 10;
backend  | # Run migrations
backend  | alembic upgrade head
backend  |
backend  | [2022-10-18 05:41:31 +0000] [1] [INFO] Starting gunicorn 20.1.0
backend  | [2022-10-18 05:41:31 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
backend  | [2022-10-18 05:41:31 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
backend  | [2022-10-18 05:41:31 +0000] [7] [INFO] Booting worker with pid: 7
backend  | [2022-10-18 05:41:31 +0000] [8] [INFO] Booting worker with pid: 8
backend  | [2022-10-18 05:41:31 +0000] [9] [INFO] Booting worker with pid: 9
backend  | [2022-10-18 05:41:32 +0000] [10] [INFO] Booting worker with pid: 10
backend  | [2022-10-18 05:41:32 +0000] [8] [INFO] Started server process [8]
backend  | [2022-10-18 05:41:32 +0000] [8] [INFO] Waiting for application startup.
backend  | [2022-10-18 05:41:32 +0000] [7] [INFO] Started server process [7]
backend  | [2022-10-18 05:41:32 +0000] [7] [INFO] Waiting for application startup.
backend  | [2022-10-18 05:41:32 +0000] [9] [INFO] Started server process [9]
backend  | [2022-10-18 05:41:32 +0000] [9] [INFO] Waiting for application startup.
backend  | [2022-10-18 05:41:32 +0000] [10] [INFO] Started server process [10]
backend  | [2022-10-18 05:41:32 +0000] [10] [INFO] Waiting for application startup.
```

**Comment by jda5** [comment]
Okay, it's got nothing to do with the database start up. I created a `prestart.sh` script that slept for a minute. The database fully loaded but the workers still were waiting for the application to startup.

**Comment by jda5** [comment]
After further exploration, this has nothing to do with the database and everything to do with extra hosts defined in the `docker-compose` file:

```    
extra_hosts:
      - "host.docker.internal:host-gateway"
```

I am starting to see why this worked on my Mac (for which I didn't need the extra host) and why it isn't working on my server.

Removing this line started the application, but of course caused everything else to crash.

```
backend  | [2022-10-18 08:23:13 +0000] [1] [INFO] Starting gunicorn 20.1.0
backend  | [2022-10-18 08:23:13 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
backend  | [2022-10-18 08:23:13 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
backend  | [2022-10-18 08:23:13 +0000] [7] [INFO] Booting worker with pid: 7
backend  | [2022-10-18 08:23:13 +0000] [8] [INFO] Booting worker with pid: 8
backend  | [2022-10-18 08:23:13 +0000] [9] [INFO] Booting worker with pid: 9
backend  | [2022-10-18 08:23:14 +0000] [10] [INFO] Booting worker with pid: 10
backend  | [2022-10-18 08:23:14 +0000] [9] [INFO] Started server process [9]
backend  | [2022-10-18 08:23:14 +0000] [9] [INFO] Waiting for application startup.
backend  | [2022-10-18 08:23:14 +0000] [7] [INFO] Started server process [7]
backend  | [2022-10-18 08:23:14 +0000] [7] [INFO] Waiting for application startup.
backend  | [2022-10-18 08:23:14 +0000] [9] [ERROR] Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 527, in _connect
backend  |     self._reader, self._writer = await \
backend  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
backend  |     return await fut
backend  |   File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 88, in _open_connection
backend  |     transport, _ = await loop.create_connection(
backend  |   File "uvloop/loop.pyx", line 1978, in create_connection
backend  | socket.gaierror: [Errno -2] Name or service not known
backend  |
backend  | The above exception was the direct cause of the following exception:
backend  |
backend  | Traceback (most recent call last):
backend  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 645, in lifespan
backend  |     async with self.lifespan_context(app):
backend  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 540, in __aenter__
backend  |     await self._router.startup()
backend  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 622, in startup
backend  |     await handler()
backend  |   File "/app/main.py", line 31, in startup
backend  |     await db.connect()
backend  |   File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 82, in connect
backend  |     await self._backend.connect()
backend  |   File "/usr/local/lib/python3.9/site-packages/databases/backends/mysql.py", line 66, in connect
backend  |     self._pool = await aiomysql.create_pool(
backend  |   File "/usr/local/lib/python3.9/site-packages/aiomysql/pool.py", line 29, in _create_pool
backend  |     await pool._fill_free_pool(False)
backend  |   File "/usr/local/lib/python3.9/site-packages/aiomysql/pool.py", line 182, in _fill_free_pool
backend  |     conn = await connect(echo=self._echo, loop=self._loop,
backend  |   File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 75, in _connect
backend  |     await conn._connect()
backend  |   File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 558, in _connect
backend  |     raise OperationalError(2003,
backend  | pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'host.docker.internal'")
```

Any ideas what I can try?

**Comment by jda5** [comment]
I am starting to feel like this is an issue with **databases** or possibly even my server provider. I have since removed:

```
 db:                           # The MySQL service definition
    container_name: db
    image: mysql:latest         # Fetch the image from the offical MySQL Docker page
    restart: always             # Restart the database upon shutdown
    environment:                # Define enironment variables
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"             # Cannot use port 3306 as it is being taken by an existing instance of MySQL
```

From the `docker-compose` file as this actually wasn't needed (I am not looking to create a new database).

I still receive the familiar error:

```
backend  | Checking for script in /app/prestart.sh
backend  | Running script /app/prestart.sh
backend  | Running inside /app/prestart.sh, you could add migrations to this file, e.g.:
backend  |
backend  | #! /usr/bin/env bash
backend  |
backend  | # Let the DB start
backend  | sleep 10;
backend  | # Run migrations
backend  | alembic upgrade head
backend  |
backend  | [2022-10-18 10:20:27 +0000] [1] [INFO] Starting gunicorn 20.1.0
backend  | [2022-10-18 10:20:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
backend  | [2022-10-18 10:20:27 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
backend  | [2022-10-18 10:20:27 +0000] [7] [INFO] Booting worker with pid: 7
backend  | [2022-10-18 10:20:27 +0000] [8] [INFO] Booting worker with pid: 8
backend  | [2022-10-18 10:20:27 +0000] [9] [INFO] Booting worker with pid: 9
backend  | [2022-10-18 10:20:27 +0000] [10] [INFO] Booting worker with pid: 10
backend  | [2022-10-18 10:20:28 +0000] [7] [INFO] Started server process [7]
backend  | [2022-10-18 10:20:28 +0000] [7] [INFO] Waiting for application startup.
backend  | [2022-10-18 10:20:28 +0000] [8] [INFO] Started server process [8]
backend  | [2022-10-18 10:20:28 +0000] [8] [INFO] Waiting for application startup.
backend  | [2022-10-18 10:20:28 +0000] [9] [INFO] Started server process [9]
backend  | [2022-10-18 10:20:28 +0000] [9] [INFO] Waiting for application startup.
backend  | [2022-10-18 10:20:28 +0000] [10] [INFO] Started server process [10]
backend  | [2022-10-18 10:20:28 +0000] [10] [INFO] Waiting for application startup.
```

But I think what is happening is the program is hanging at this point in the **database.py** file:

```
db = databases.Database(
    f'mysql://{_user}:{_password}@{_host}/{_database}?port={_port}'
)
```

I'll keep digging but like I said I no longer thing this is an issue with the FastAPI image.

**Comment by jda5** [comment]
I tried changing the `docker-compose` file to:

```
services:

  backend:
    container_name: backend
    build: ./
    restart: always
    ports:
      - "8080:80"
    network_mode: "host"
```

And then the host in the database URI to: `127.0.0.0` but this produced a new error:

```
Attaching to backend
backend  | Checking for script in /app/prestart.sh
backend  | Running script /app/prestart.sh
backend  | Running inside /app/prestart.sh, you could add migrations to this file, e.g.:
backend  |
backend  | #! /usr/bin/env bash
backend  |
backend  | # Let the DB start
backend  | sleep 10;
backend  | # Run migrations
backend  | alembic upgrade head
backend  |
backend  | [2022-10-18 15:44:43 +0000] [1] [INFO] Starting gunicorn 20.1.0
backend  | [2022-10-18 15:44:43 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 80)
backend  | [2022-10-18 15:44:43 +0000] [1] [ERROR] Retrying in 1 second.
backend  | [2022-10-18 15:44:44 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 80)
backend  | [2022-10-18 15:44:44 +0000] [1] [ERROR] Retrying in 1 second.
backend  | [2022-10-18 15:44:45 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 80)
backend  | [2022-10-18 15:44:45 +0000] [1] [ERROR] Retrying in 1 second.
backend  | [2022-10-18 15:44:46 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 80)
backend  | [2022-10-18 15:44:46 +0000] [1] [ERROR] Retrying in 1 second.
backend  | [2022-10-18 15:44:47 +0000] [1] [ERROR] Connection in use: ('0.0.0.0', 80)
backend  | [2022-10-18 15:44:47 +0000] [1] [ERROR] Retrying in 1 second.
```

This is particularly weird for two reasons:

1. I specified port 8080 in my docker-compose file and not 80
2. Port 80 is not in use! It's open. Running reveals

```
tcp    LISTEN     0      128       *:80                    *:*                   users:(("httpd",pid=29213,fd=3),("httpd",pid=29202,fd=3),("httpd",pid=29184,fd=3),("httpd",pid=29157,fd=3),("httpd",pid=29155,fd=3),("httpd",pid=29152,fd=3),("httpd",pid=4823,fd=3))
tcp    LISTEN     0      128    [::]:80                 [::]:*                   users:(("httpd",pid=29213,fd=4),("httpd",pid=29202,fd=4),("httpd",pid=29184,fd=4),("httpd",pid=29157,fd=4),("httpd",pid=29155,fd=4),("httpd",pid=29152,fd=4),("httpd",pid=4823,fd=4))
```

Any ideas as to what I can try next?

**Comment by jda5** [comment]
This issue was completely with my hosting provider.

**Comment by tiangolo** [comment]
Thanks for coming back to report and close the issue!
