### ISSUE TITLE
how to debug an application

### ISSUE THREAD

**Issue by talnagar** [tiangolo/uvicorn-gunicorn-fastapi-docker#21]
Hi
Is it possible debugging an app (for example using the pycharm or vscode debugger)?
The only solution I found so far is changing the log level to DEBUG but it's not enough for properly debugging an API

**Comment by geekkun** [comment]
My workaround is to add 
`import uvicorn`
and at the bottom of the `main.py`
```
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

And run it as a normal python file without docker at all. In pro version of pycharm it is possible to setup docker as a remote debugger, but I don't use that feature.

**Comment by talnagar** [comment]
thank you. I'll check out pycharm

**Comment by Sihomiri** [comment]
I do all of the above but then I get the following error when hitting the endpoint.

INFO:     127.0.0.1:50311 - "GET /coordinate/2 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/fastapi/applications.py", line 139, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/fastapi/routing.py", line 111, in app
    raw_response = await dependant.call(**values)
  File "/Users/sihomiri/Documents/GPS/app.py", line 26, in get_coordinate
    data = await dal.find("coordinates",{"id":id})
  File "/Users/sihomiri/Documents/GPS/data_acces_layer.py", line 69, in find
    for result in await cursor.to_list(length=100):
RuntimeError: Task <Task pending coro=<RequestResponseCycle.run_asgi() running at /Users/sihomiri/anaconda2/envs/py37/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py:385> cb=[set.discard()]> got Future <Future pending> attached to a different loop

**Comment by mr-bjerre** [comment]
@geekkun that does not support auto-reload though, right?

**Comment by tiangolo** [comment]
@Kludex implemented integrated support in the official Python VS Code extension: https://github.com/microsoft/vscode-python/pull/14606

Meanwhile, you can try these snippets: https://github.com/microsoft/vscode-python/issues/14247#issuecomment-703620291
