### ISSUE TITLE
container build fails with pydantic-settings

### ISSUE THREAD

**Issue by wmclendon** [tiangolo/uvicorn-gunicorn-fastapi-docker#248]
hello,

i am working on updating to pydantic v2, and i've found that when I have pydantic-settings in my requirements.txt file, I get an error when building the container.  Best I can tell its failing on PyYaml, a dependency of pydantic-settings -- below is the error contents:

```
Building <redacted>
[+] Building 9.4s (9/9) FINISHED                                                                                                                           docker:default
 => [internal] load build definition from Dockerfile                                                                                                                 0.0s
 => => transferring dockerfile: 224B                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/tiangolo/uvicorn-gunicorn-fastapi:latest                                                                                  0.0s
 => [1/5] FROM docker.io/tiangolo/uvicorn-gunicorn-fastapi:latest                                                                                                    0.0s
 => [internal] load build context                                                                                                                                    0.0s
 => => transferring context: 5.48kB                                                                                                                                  0.0s
 => CACHED [2/5] COPY ./requirements.txt requirements.txt                                                                                                            0.0s
 => CACHED [3/5] COPY ./app /app                                                                                                                                     0.0s
 => CACHED [4/5] RUN pip install --upgrade pip                                                                                                                       0.0s
 => ERROR [5/5] RUN pip install --no-cache-dir -r requirements.txt                                                                                                   9.4s
------                                                                                                                                                                    
 > [5/5] RUN pip install --no-cache-dir -r requirements.txt:                                                                                                              
0.659 Requirement already satisfied: fastapi in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.88.0)                                      
0.664 Requirement already satisfied: pydantic in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.10.12)                                    
0.754 Collecting pydantic-settings (from -r requirements.txt (line 3))                                                                                                    
0.755   Obtaining dependency information for pydantic-settings from https://files.pythonhosted.org/packages/9c/3e/3311eeab406db6116e7f2d4ed9b05c2811282143efa55feb12cc513a8b84/pydantic_settings-2.0.2-py3-none-any.whl.metadata
0.814   Downloading pydantic_settings-2.0.2-py3-none-any.whl.metadata (2.9 kB)
0.818 Requirement already satisfied: uvicorn[standard] in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.20.0)
0.838 Collecting python-jose[cryptography] (from -r requirements.txt (line 5))
0.845   Downloading python_jose-3.3.0-py2.py3-none-any.whl (33 kB)
0.852 Requirement already satisfied: httpx in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.24.1)
0.888 Collecting aioftp (from -r requirements.txt (line 7))
0.894   Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
0.898 Requirement already satisfied: python-dotenv in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (1.0.0)
0.913 Collecting librouteros (from -r requirements.txt (line 9))
0.919   Downloading librouteros-3.2.1.tar.gz (13 kB)
0.927   Installing build dependencies: started
3.052   Installing build dependencies: finished with status 'done'
3.054   Getting requirements to build wheel: started
3.239   Getting requirements to build wheel: finished with status 'done'
3.245   Preparing metadata (pyproject.toml): started
3.484   Preparing metadata (pyproject.toml): finished with status 'done'
3.508 Collecting netaddr (from -r requirements.txt (line 10))
3.514   Downloading netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
3.539      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 86.7 MB/s eta 0:00:00
3.571 Collecting pynetbox (from -r requirements.txt (line 11))
3.577   Downloading pynetbox-7.0.1-py3-none-any.whl (33 kB)
3.683 Collecting mysql-connector-python (from -r requirements.txt (line 12))
3.683   Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/55/8e/1270601b42d40c4fb0191fd9043430889510bdbc711c482b12e6f66099e2/mysql_connector_python-8.1.0-cp311-cp311-manylinux_2_17_x86_64.whl.metadata
3.689   Downloading mysql_connector_python-8.1.0-cp311-cp311-manylinux_2_17_x86_64.whl.metadata (2.0 kB)
3.727 Collecting psycopg[binary] (from -r requirements.txt (line 13))
3.727   Obtaining dependency information for psycopg[binary] from https://files.pythonhosted.org/packages/01/27/89a0024ac7e7f872eccb5785707d4bc2162b8da8cb2fd4202813969a9952/psycopg-3.1.10-py3-none-any.whl.metadata
3.732   Downloading psycopg-3.1.10-py3-none-any.whl.metadata (3.6 kB)
3.790 Requirement already satisfied: starlette==0.22.0 in /usr/local/lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 1)) (0.22.0)
3.801 Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.11/site-packages (from starlette==0.22.0->fastapi->-r requirements.txt (line 1)) (3.7.1)
3.809 Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.11/site-packages (from pydantic->-r requirements.txt (line 2)) (4.7.1)
4.076 INFO: pip is looking at multiple versions of pydantic-settings to determine which version is compatible with other requirements. This could take a while.
4.084 Collecting pydantic-settings (from -r requirements.txt (line 3))
4.084   Obtaining dependency information for pydantic-settings from https://files.pythonhosted.org/packages/05/fe/ed5f64a49b72af12244dec414e85cb006b5e011325e1ae7e373128a33444/pydantic_settings-2.0.1-py3-none-any.whl.metadata
4.096   Downloading pydantic_settings-2.0.1-py3-none-any.whl.metadata (2.8 kB)
4.109   Obtaining dependency information for pydantic-settings from https://files.pythonhosted.org/packages/24/3e/a7733506319a483c04f88719b817c4b6f2c5c22be9ff2c27b1fa89d670de/pydantic_settings-2.0.0-py3-none-any.whl.metadata
4.115   Downloading pydantic_settings-2.0.0-py3-none-any.whl.metadata (2.9 kB)
4.171   Downloading pydantic_settings-1.99-py3-none-any.whl (9.4 kB)
4.225   Downloading pydantic_settings-0.2.5-py3-none-any.whl (21 kB)
4.263 Collecting attrs<20.0,>=19.1 (from pydantic-settings->-r requirements.txt (line 3))
4.268   Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
4.287 Collecting class-doc==0.2.0b (from pydantic-settings->-r requirements.txt (line 3))
4.292   Downloading class_doc-0.2.0b0-py3-none-any.whl (4.4 kB)
4.372 Collecting pyyaml<6.0.0,>=5.1.2 (from pydantic-settings->-r requirements.txt (line 3))
4.378   Downloading PyYAML-5.4.1.tar.gz (175 kB)
4.382      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 196.7 MB/s eta 0:00:00
4.543   Installing build dependencies: started
8.498   Installing build dependencies: finished with status 'done'
8.498   Getting requirements to build wheel: started
8.980   Getting requirements to build wheel: finished with status 'error'
8.989   error: subprocess-exited-with-error
8.989   
8.989   × Getting requirements to build wheel did not run successfully.
8.989   │ exit code: 1
8.989   ╰─> [68 lines of output]
8.989       /tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
8.989       !!
8.989       
8.989               ********************************************************************************
8.989               The license_file parameter is deprecated, use license_files instead.
8.989       
8.989               By 2023-Oct-30, you need to update your project and remove deprecated calls
8.989               or your builds will no longer be supported.
8.989       
8.989               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
8.989               ********************************************************************************
8.989       
8.989       !!
8.989         parsed = self.parsers.get(option_name, lambda x: x)(value)
8.989       running egg_info
8.989       writing lib3/PyYAML.egg-info/PKG-INFO
8.989       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
8.989       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
8.989       Traceback (most recent call last):
8.989         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
8.989           main()
8.989         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
8.989           json_out['return_val'] = hook(**hook_input['kwargs'])
8.989                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.989         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
8.989           return hook(config_settings)
8.989                  ^^^^^^^^^^^^^^^^^^^^^
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
8.989           return self._get_build_requires(config_settings, requirements=['wheel'])
8.989                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
8.989           self.run_setup()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
8.989           exec(code, locals())
8.989         File "<string>", line 271, in <module>
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
8.989           return distutils.core.setup(**attrs)
8.989                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
8.989           return run_commands(dist)
8.989                  ^^^^^^^^^^^^^^^^^^
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
8.989           dist.run_commands()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
8.989           self.run_command(cmd)
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
8.989           super().run_command(command)
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
8.989           cmd_obj.run()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
8.989           self.find_sources()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
8.989           mm.run()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
8.989           self.add_defaults()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
8.989           sdist.add_defaults(self)
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
8.989           super().add_defaults()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
8.989           self._add_defaults_ext()
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
8.989           self.filelist.extend(build_ext.get_source_files())
8.989                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8.989         File "<string>", line 201, in get_source_files
8.989         File "/tmp/pip-build-env-39vre7zy/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
8.989           raise AttributeError(attr)
8.989       AttributeError: cython_sources
8.989       [end of output]
8.989   
8.989   note: This error originates from a subprocess, and is likely not a problem with pip.
8.991 error: subprocess-exited-with-error
8.991 
8.991 × Getting requirements to build wheel did not run successfully.
8.991 │ exit code: 1
8.991 ╰─> See above for output.
8.991 
8.991 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:6
--------------------
   4 |     COPY ./app /app
   5 |     RUN pip install --upgrade pip
   6 | >>> RUN pip install --no-cache-dir -r requirements.txt
   7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
```

by changing my import to use `from pydantic.v1 import BaseSettings` and commenting out `pydantic-settings` from requirements.txt, the build succeeds.

If there is additional info you need I can try to provide -- thanks for all you do!

**Comment by wmclendon** [comment]
I believe I have found the issue, I will leave this here closed in case it helps anyone else.

I needed to change my Dockerfile to have `--upgrade`` as part of installing requirements:

```
RUN pip install --upgrade --no-cache-dir -r requirements.txt
```

I think what was happening is the container has Pydantic v1 in it, and there was some kind of conflict.  Because I did not have the `--upgrade` flag initially, pip wasn't updating all of my dependencies as I expected.

I actually found this on a different system where I actually ran the container and it was failing because it didn't know what `pydantic.v1` was and I saw in the container pip list it still had pydantic v1 installed rather than v2.
